# WSO2 Identity Server with PostgreSQL JDBC Driver
#
# Uses wso2/wso2is:7.2.0 as the base image because the 7.3.0 GA image
# is not yet published on Docker Hub. When it becomes available, update to:
#
#   FROM wso2/wso2is:7.3.0
#   ... /home/wso2carbon/wso2is-7.3.0/repository/components/lib/...
#
FROM wso2/wso2is:7.2.0

USER root
RUN wget -q -O /home/wso2carbon/wso2is-7.2.0/repository/components/lib/postgresql-42.7.3.jar \
    https://jdbc.postgresql.org/download/postgresql-42.7.3.jar && \
    chown wso2carbon:wso2 /home/wso2carbon/wso2is-7.2.0/repository/components/lib/postgresql-42.7.3.jar
USER wso2carbon
